// Code generated by protoc-gen-go. DO NOT EDIT.
// source: number.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InputNumber struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputNumber) Reset()         { *m = InputNumber{} }
func (m *InputNumber) String() string { return proto.CompactTextString(m) }
func (*InputNumber) ProtoMessage()    {}
func (*InputNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6c6c2f2b9341206, []int{0}
}

func (m *InputNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputNumber.Unmarshal(m, b)
}
func (m *InputNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputNumber.Marshal(b, m, deterministic)
}
func (m *InputNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputNumber.Merge(m, src)
}
func (m *InputNumber) XXX_Size() int {
	return xxx_messageInfo_InputNumber.Size(m)
}
func (m *InputNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_InputNumber.DiscardUnknown(m)
}

var xxx_messageInfo_InputNumber proto.InternalMessageInfo

func (m *InputNumber) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type HelloOutput struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloOutput) Reset()         { *m = HelloOutput{} }
func (m *HelloOutput) String() string { return proto.CompactTextString(m) }
func (*HelloOutput) ProtoMessage()    {}
func (*HelloOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6c6c2f2b9341206, []int{1}
}

func (m *HelloOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloOutput.Unmarshal(m, b)
}
func (m *HelloOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloOutput.Marshal(b, m, deterministic)
}
func (m *HelloOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloOutput.Merge(m, src)
}
func (m *HelloOutput) XXX_Size() int {
	return xxx_messageInfo_HelloOutput.Size(m)
}
func (m *HelloOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloOutput.DiscardUnknown(m)
}

var xxx_messageInfo_HelloOutput proto.InternalMessageInfo

func (m *HelloOutput) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*InputNumber)(nil), "proto.InputNumber")
	proto.RegisterType((*HelloOutput)(nil), "proto.HelloOutput")
}

func init() {
	proto.RegisterFile("number.proto", fileDescriptor_e6c6c2f2b9341206)
}

var fileDescriptor_e6c6c2f2b9341206 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x2b, 0xcd, 0x4d,
	0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xf2, 0x5c, 0xdc,
	0x9e, 0x79, 0x05, 0xa5, 0x25, 0x7e, 0x60, 0x39, 0x21, 0x01, 0x2e, 0xe6, 0xbc, 0xd2, 0x5c, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x10, 0x53, 0x49, 0x93, 0x8b, 0xdb, 0x23, 0x35, 0x27, 0x27,
	0xdf, 0xbf, 0xb4, 0xa4, 0xa0, 0xb4, 0x44, 0x48, 0x8a, 0x8b, 0x23, 0xbd, 0x28, 0x35, 0xb5, 0x24,
	0x33, 0x2f, 0x1d, 0xac, 0x8a, 0x33, 0x08, 0xce, 0x37, 0x72, 0xe4, 0x62, 0x83, 0x1a, 0x63, 0x0e,
	0xd5, 0x04, 0xe5, 0x0a, 0x41, 0xec, 0xd4, 0x43, 0xb2, 0x49, 0x0a, 0x26, 0x86, 0x64, 0xb8, 0x12,
	0x43, 0x12, 0x1b, 0x58, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x56, 0x63, 0x3a, 0xac,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NumberClient is the client API for Number service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NumberClient interface {
	HelloNumber(ctx context.Context, in *InputNumber, opts ...grpc.CallOption) (*HelloOutput, error)
}

type numberClient struct {
	cc grpc.ClientConnInterface
}

func NewNumberClient(cc grpc.ClientConnInterface) NumberClient {
	return &numberClient{cc}
}

func (c *numberClient) HelloNumber(ctx context.Context, in *InputNumber, opts ...grpc.CallOption) (*HelloOutput, error) {
	out := new(HelloOutput)
	err := c.cc.Invoke(ctx, "/proto.Number/HelloNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NumberServer is the server API for Number service.
type NumberServer interface {
	HelloNumber(context.Context, *InputNumber) (*HelloOutput, error)
}

// UnimplementedNumberServer can be embedded to have forward compatible implementations.
type UnimplementedNumberServer struct {
}

func (*UnimplementedNumberServer) HelloNumber(ctx context.Context, req *InputNumber) (*HelloOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloNumber not implemented")
}

func RegisterNumberServer(s *grpc.Server, srv NumberServer) {
	s.RegisterService(&_Number_serviceDesc, srv)
}

func _Number_HelloNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberServer).HelloNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Number/HelloNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberServer).HelloNumber(ctx, req.(*InputNumber))
	}
	return interceptor(ctx, in, info, handler)
}

var _Number_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Number",
	HandlerType: (*NumberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloNumber",
			Handler:    _Number_HelloNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "number.proto",
}
